### ISSUE TITLE
No admin binding?

### ISSUE THREAD

**Issue by patriclougheed** [trilbymedia/grav-plugin-login-ldap#1]
So this only has anon directory search? I see no way to binddn credentials for lookup. I would like to suggest this as an enhancement. My servers do not allow anon searching.

**Comment by w00fz** [comment]
Why do you say so? 

I just tested on our dev server with anonymous bind disabled and I was able to log in both frontend/backend of Grav no problem. Did you try and are you getting issues?

**Comment by fheslouin** [comment]
I have the same question. I'm using LDAP synology disk station with anonymous bind disabled. 
I'm getting 
```
Invalid credentials [] []
```
each try I'm trying to log in.

How can I bind with this plugin without first bind with root ?

**Comment by theo2thief** [comment]
I use a Synology NAS to run a Windows ActiveDirectory domain. 
I had to make sure the NAS was using a valid certificate for the domain and make sure Apache had loaded up the CA bundle.

After I got the connection to work I found that I could not bind with the default user DN, as Windows AD does not populate the UID attributes.

Using [username]@ad.example.com worked for me. But I was then unable to use groups, as the query for that relies on the memberUid attribute, which is not populated by Windows AD.

To query for groups a user is a member of you need to use the distinguishedName attribute, which was not available. To get around this I made some modifications to the plugin that allows me to add the distinguishedName of the bound user to the group query. (you can see these small modifications in my fork of this repository)

Here is my final configuration:

```
enabled: true
host: ad.example.com
port: 636
version: 3
ssl: true
start_tls: true
opt_referrals: true
user_dn: '[username]@ad.example.com'
search_dn: 'OU=Users,OU=Example,DC=ad,DC=example,DC=com'
group_dn: 'OU=Groups,OU=Example,DC=ad,DC=example,dc=com'
group_query: '(&(objectClass=group)(member:1.2.840.113556.1.4.1941:=[dn]))'
group_indentifier: cn
map_username: samAccountName
map_fullname: 'givenName sn'
map_email: mail
map_dn: distinguishedName
save_grav_user: false
store_ldap_data: false
default_access_levels:
  groups:
    - ldap_users
  access:
    site:
      login: 'false'
    groups: "Grav-Admin:\r\n    admin:\r\n      login: true\r\n      super: true\r\n    site:\r\n      login: true\r\nGrav-Read:\r\n  site:\r\n    login: true\r\nGrav-Author:\r\n  site:\r\n    login: true\r\n  admin:\r\n    login: true\r\n    pages: true"
```

Hope this helps.
