### ISSUE TITLE
login-ldap.yaml syntax

### ISSUE THREAD

**Issue by boutmos** [trilbymedia/grav-plugin-login-ldap#11]
hi ! ,

I try to make a group mapping when a LDAP user is login in on my grav' site but, I can not.

So I wonder if the syntax below on the `login-ldap.yaml` file is good or not.

Here is my `groups.yaml` file

```yaml
adminsys:
  groupname: adminsys
  readableName: adminsys
  description: 'Groupe pour les adminsys'
  icon: cogs
  access:
    site:
      login: 'true'
    admin:
      super: 'true'
      login: 'true'
      cache: 'true'
      configuration: 'true'
      configuration_system: 'true'
      configuration_site: 'true'
      configuration_media: 'true'
      configuration_info: 'true'
      settings: 'true'
      pages: 'true'
      maintenance: 'true'
      statistics: 'true'
      plugins: 'true'
      themes: 'true'
      tools: 'true'
      users: 'true'
    admin-addon-user-manager:
      users: 'true'
      groups: 'true'
      users_expert: 'true'
exterieur:
  groupname: exterieur
  readableName: exterieur
  description: 'Groupe pour les membres exterieurs'
  icon: user-circle
  access:
    site:
      login: 'true'
    admin: {  }
    admin-addon-user-manager: {  }
etudiant:
  groupname: etudiant
  readableName: etudiant
  description: 'Groupe pour les étudiants'
  icon: graduation-cap
  access:
    site:
      login: 'true'
    admin: {  }
    admin-addon-user-manager: {  }
vacataire:
  groupname: vacataire
  readableName: vacataire
  description: 'Groupe pour les vacataires'
  icon: user-circle
  access:
    site:
      login: 'true'
    admin: {  }
    admin-addon-user-manager: {  }
aitos:
  groupname: aitos
  readableName: secretaire
  description: 'Groupe pour les secrétaires administratifs et pédagogiques'
  icon: user-circle-o
  access:
    site:
      login: 'true'
    admin: {  }
    admin-addon-user-manager: {  }
enseign:
  groupname: enseign
  readableName: enseignant
  description: 'Groupe pour les enseignants'
  icon: user-circle
  access:
    site:
      login: 'true'
    admin: {  }
    admin-addon-user-manager: {  }
```
and here, the `login-ldap.yaml` one : 

```yaml
default_access_levels:
  groups:
    - ldap_users
  access:
    site:
      login: 'true'
    groups: "admin:\r\n    admin:\r\n      login: true\r\n      super: true\r\n    site:\r\n      login: true\r\nuser:\r\n  site:\r\n    login: true\r\nexterieur:\r\n  site:\r\n    login: true\r\naitos:\r\n  site:\r\n    login: true\r\nvacataire:\r\n  site:\r\n    login: true\r\nadminsys:\r\n    admin:\r\n      login: true\r\n      super: true\r\n    site:\r\n      login: true"
```
